export const REQUEST_START ="REQUEST_START";
export const REQUEST_FAIL = "REQUEST_FAIL";
export const MOVIES_SUCCCESS = "MOVIES_SUCCCESS";
export const MOVIE_SUCCCESS = "MOVIE_SUCCCESS";
export const MOVIE_ADD = "MOVIE_ADD" 
export const MOVIE_DELETE = "MOVIE_DELETE" 
export const MOVIE_EDIT = "MOVIE_EDIT" 