export const AUTH_LOGOUT_INIT = "AUTH_LOGOUT_INIT"
export const CHECK_TIME_OUT_INIT = "CHECK_TIME_OUT_INIT"
export const AUTH_START_INIT = "AUTH_START_INIT"
export const CHECK_TIME_OUT_STATE_INIT = "CHECK_TIME_OUT_STATE_INIT"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT";